version: '3.8'
services:
  app:
    build: ./docker
    ports:
      - "3000:3000"
    environment:
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    command: npm run dev
